In [258]:
import pandas as pd
import numpy as np

In [260]:
df = pd.read_csv('2024.csv')
df.head()

,Unnamed: 0,Outcome,Rbi,Bases,Batter_id,Batter_name,Pitcher,Isout,Outs,homeScore,awayScore,inning,isTopInning,runner_pos,Date
0,0,field_out,0,Empty,453568,Charlie Blackmon,vs_LHP,True,1,0,0,1,True,[0],2024-04-01
1,1,strikeout,0,Empty,663898,Brendan Rodgers,vs_LHP,True,2,0,0,1,True,[0],2024-04-01
2,2,field_out,0,Empty,666134,Nolan Jones,vs_LHP,True,3,0,0,1,True,[0],2024-04-01
3,3,walk,0,Empty,664023,Ian Happ,vs_RHP,False,0,0,0,1,False,[0],2024-04-01
4,4,field_out,0,Men_On,673548,Seiya Suzuki,vs_RHP,True,1,0,0,1,False,"[0, 1]",2024-04-01

In [262]:
df.drop('Unnamed: 0', axis = 1, inplace = True)
df.head()

,Outcome,Rbi,Bases,Batter_id,Batter_name,Pitcher,Isout,Outs,homeScore,awayScore,inning,isTopInning,runner_pos,Date
0,field_out,0,Empty,453568,Charlie Blackmon,vs_LHP,True,1,0,0,1,True,[0],2024-04-01
1,strikeout,0,Empty,663898,Brendan Rodgers,vs_LHP,True,2,0,0,1,True,[0],2024-04-01
2,field_out,0,Empty,666134,Nolan Jones,vs_LHP,True,3,0,0,1,True,[0],2024-04-01
3,walk,0,Empty,664023,Ian Happ,vs_RHP,False,0,0,0,1,False,[0],2024-04-01
4,field_out,0,Men_On,673548,Seiya Suzuki,vs_RHP,True,1,0,0,1,False,"[0, 1]",2024-04-01

In [264]:
df.shape

(181374, 14)

In [266]:
df['runner_pos'].unique()

array(['[0]', '[0, 1]', '[0, 3, 1]', '[0, 2, 1]', '[0, 2]',
       '[0, 3, 2, 1]', '[0, 3, 2]', '[0, 3]', '[0, 1, 2]', '[0, 3, 1, 2]',
       '[0, 3, 1, 2, 1]', '[0, 1, 1, 2]', '[0, 1, 2, 3, 1]',
       '[0, 1, 2, 1]', '[0, 1, 3]', '[0, 2, 3]', '[0, 2, 2, 3, 1]',
       '[0, 2, 3, 2, 1]', '[0, 2, 3, 2]', '[0, 2, 3, 1]', '[0, 1, 3, 1]',
       '[0, 1, 1]', '[0, 1, 3, 2, 1]', '[0, 1, 3, 2]', '[0, 1, 1, 3]',
       '[0, 1, 2, 3]', '[0, 1, 2, 2, 1]', '[0, 3, 1, 1]',
       '[0, 2, 2, 1, 3]', '[0, 2, 1, 3]', '[0, 2, 2, 3]', '[0, 2, 2]',
       '[0, 2, 2, 1]', '[0, 1, 3, 1, 2, 1]', '[0, 1, 1, 3, 2, 1]',
       '[0, 1, 1, 1, 3]', '[0, 3, 3, 2, 1]', '[0, 3, 3, 2]',
       '[0, 3, 1, 1, 2]', '[0, 1, 1, 2, 3]', '[0, 3, 3]',
       '[0, 1, 1, 2, 3, 1]', '[0, 1, 1, 3, 2]', '[0, 1, 2, 1, 3]',
       '[0, 1, 2, 2]'], dtype=object)

In [268]:
# simplifying runner_pos to make future calc easier

# to man on 2nd and 3rd
df.loc[df['runner_pos'] == '[0, 3, 1, 2]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 2, 3]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 2, 3, 2]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 1, 3, 2]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 1, 2, 3]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 2, 2, 3]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 3, 3, 2]', 'runner_pos'] = '[0, 3, 2]'
df.loc[df['runner_pos'] == '[0, 1, 1, 2, 3]', 'runner_pos'] = '[0, 3, 2]'

# to 1st and 2nd
df.loc[df['runner_pos'] == '[0, 1, 1, 2]', 'runner_pos'] = '[0, 2, 1]'
df.loc[df['runner_pos'] == '[0, 1, 2]', 'runner_pos'] = '[0, 2, 1]'
df.loc[df['runner_pos'] == '[0, 1, 2, 1]', 'runner_pos'] = '[0, 2, 1]'
df.loc[df['runner_pos'] == '[0, 1, 2, 2, 1]', 'runner_pos'] = '[0, 2, 1]'
df.loc[df['runner_pos'] == '[0, 2, 2, 1]', 'runner_pos'] = '[0, 2, 1]'
df.loc[df['runner_pos'] == '[0, 1, 2, 2]', 'runner_pos'] = '[0, 2, 1]'

# to bases empty
df.loc[df['runner_pos'] == '[0, 1, 1, 1, 3]', 'runner_pos'] = '[0]'

# to runner on first
df.loc[df['runner_pos'] == '[0, 1, 1]', 'runner_pos'] = '[0, 1]'

# to runner on 2nd
df.loc[df['runner_pos'] == '[0, 2, 2]', 'runner_pos'] = '[0, 2]'

# to runner on 3rd
df.loc[df['runner_pos'] == '[0, 3, 3]', 'runner_pos'] = '[0, 3]'

# to bases loaded
df.loc[df['Bases'] == 'Loaded', 'runner_pos'] = '[0, 3, 2, 1]'

# to runner on 1st and 3rd
df.loc[df['runner_pos'] == '[0, 1, 3]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 1, 3, 1]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 1, 1, 3]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 3, 1, 1]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 2, 3, 1]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 2, 1, 3]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 1, 1, 3, 2]', 'runner_pos'] = '[0, 3, 1]'
df.loc[df['runner_pos'] == '[0, 1, 2, 1, 3]', 'runner_pos'] = '[0, 3, 1]'

In [270]:
df['runner_pos'].unique()

array(['[0]', '[0, 1]', '[0, 3, 1]', '[0, 2, 1]', '[0, 2]',
       '[0, 3, 2, 1]', '[0, 3, 2]', '[0, 3]'], dtype=object)

In [272]:
df.dtypes

Outcome        object
Rbi             int64
Bases          object
Batter_id       int64
Batter_name    object
Pitcher        object
Isout            bool
Outs            int64
homeScore       int64
awayScore       int64
inning          int64
isTopInning      bool
runner_pos     object
Date           object
dtype: object

In [274]:
df['inningRuns'] = np.empty(len(df))

In [276]:
def getInningRuns(dataframe):
    begInning = 1
    topInning = True
    begHomeRuns = 0
    begAwayRuns = 0
    awayInningRuns = 0
    homeInningRuns = 0
    begIndex = 0
    
    for i in range(len(dataframe)):
    
        if (dataframe.loc[i, 'inning'] != begInning) | (dataframe.loc[i, 'isTopInning'] != topInning):
            
            if (dataframe.loc[(i-1), 'isTopInning'] == True):
                awayInningRuns = dataframe.loc[(i-1), 'awayScore'] - begAwayRuns
                for j in range(begIndex, i, 1):
                    dataframe.loc[j, 'inningRuns'] = awayInningRuns
                
            elif (dataframe.loc[(i-1), 'isTopInning'] == False):
                homeInningRuns = dataframe.loc[(i-1), 'homeScore'] - begHomeRuns
                for j in range(begIndex, i, 1):
                    dataframe.loc[j, 'inningRuns'] = homeInningRuns
            
            begInning = dataframe.loc[i, 'inning'] 
            topInning = dataframe.loc[i, 'isTopInning']
            begHomeRuns = dataframe.loc[i, 'homeScore']
            begAwayRuns = dataframe.loc[i, 'awayScore']
            inningRuns = 0
            begIndex = i

In [278]:
getInningRuns(df)

In [280]:
df.head(50)

,Outcome,Rbi,Bases,Batter_id,Batter_name,Pitcher,Isout,Outs,homeScore,awayScore,inning,isTopInning,runner_pos,Date,inningRuns
0,field_out,0,Empty,453568,Charlie Blackmon,vs_LHP,True,1,0,0,1,True,[0],2024-04-01,0.0
1,strikeout,0,Empty,663898,Brendan Rodgers,vs_LHP,True,2,0,0,1,True,[0],2024-04-01,0.0
2,field_out,0,Empty,666134,Nolan Jones,vs_LHP,True,3,0,0,1,True,[0],2024-04-01,0.0
3,walk,0,Empty,664023,Ian Happ,vs_RHP,False,0,0,0,1,False,[0],2024-04-01,0.0
4,field_out,0,Men_On,673548,Seiya Suzuki,vs_RHP,True,1,0,0,1,False,"[0, 1]",2024-04-01,0.0
5,field_out,0,Men_On,641355,Cody Bellinger,vs_RHP,True,2,0,0,1,False,"[0, 1]",2024-04-01,0.0
6,single,0,Men_On,666624,Christopher Morel,vs_RHP,False,2,0,0,1,False,"[0, 1]",2024-04-01,0.0
7,force_out,0,RISP,621020,Dansby Swanson,vs_RHP,True,3,0,0,1,False,"[0, 3, 1]",2024-04-01,0.0
8,field_error,0,Empty,592178,Kris Bryant,vs_LHP,False,0,0,0,2,True,[0],2024-04-01,0.0
9,strikeout,0,Men_On,641857,Ryan McMahon,vs_LHP,True,1,0,0,2,True,"[0, 1]",2024-04-01,0.0
10,strikeout,0,Men_On,553869,Elias Díaz,vs_LHP,True,2,0,0,2,True,"[0, 1]",2024-04-01,0.0
11,field_out,0,Men_On,678662,Ezequiel Tovar,vs_LHP,True,3,0,0,2,True,"[0, 1]",2024-04-01,0.0
12,field_out,0,Empty,683737,Michael Busch,vs_RHP,True,1,0,0,2,False,[0],2024-04-01,0.0
13,field_out,0,Empty,663538,Nico Hoerner,vs_RHP,True,2,0,0,2,False,[0],2024-04-01,0.0
14,field_out,0,Empty,643565,Mike Tauchman,vs_RHP,True,3,0,0,2,False,[0],2024-04-01,0.0
15,field_out,0,Empty,660707,Elehuris Montero,vs_LHP,True,1,0,0,3,True,[0],2024-04-01,0.0
16,strikeout,0,Empty,686668,Brenton Doyle,vs_LHP,True,2,0,0,3,True,[0],2024-04-01,0.0
17,field_out,0,Empty,453568,Charlie Blackmon,vs_LHP,True,3,0,0,3,True,[0],2024-04-01,0.0
18,strikeout,0,Empty,543228,Yan Gomes,vs_RHP,True,1,0,0,3,False,[0],2024-04-01,0.0
19,field_out,0,Empty,664023,Ian Happ,vs_RHP,True,2,0,0,3,False,[0],2024-04-01,0.0
20,field_out,0,Empty,673548,Seiya Suzuki,vs_RHP,True,3,0,0,3,False,[0],2024-04-01,0.0
21,field_out,0,Empty,663898,Brendan Rodgers,vs_LHP,True,1,0,0,4,True,[0],2024-04-01,0.0
22,strikeout,0,Empty,666134,Nolan Jones,vs_LHP,True,2,0,0,4,True,[0],2024-04-01,0.0
23,strikeout,0,Empty,592178,Kris Bryant,vs_LHP,True,3,0,0,4,True,[0],2024-04-01,0.0
24,field_out,0,Empty,641355,Cody Bellinger,vs_RHP,True,1,0,0,4,False,[0],2024-04-01,0.0
25,field_out,0,Empty,666624,Christopher Morel,vs_RHP,True,2,0,0,4,False,[0],2024-04-01,0.0
26,walk,0,Empty,621020,Dansby Swanson,vs_RHP,False,2,0,0,4,False,[0],2024-04-01,0.0
27,field_out,0,Men_On,683737,Michael Busch,vs_RHP,True,3,0,0,4,False,"[0, 1]",2024-04-01,0.0
28,strikeout,0,Empty,641857,Ryan McMahon,vs_LHP,True,1,0,0,5,True,[0],2024-04-01,0.0
29,field_out,0,Empty,553869,Elias Díaz,vs_LHP,True,2,0,0,5,True,[0],2024-04-01,0.0
30,strikeout,0,Empty,678662,Ezequiel Tovar,vs_LHP,True,3,0,0,5,True,[0],2024-04-01,0.0
31,field_out,0,Empty,663538,Nico Hoerner,vs_RHP,True,1,0,0,5,False,[0],2024-04-01,0.0
32,strikeout,0,Empty,643565,Mike Tauchman,vs_RHP,True,2,0,0,5,False,[0],2024-04-01,0.0
33,field_out,0,Empty,543228,Yan Gomes,vs_RHP,True,3,0,0,5,False,[0],2024-04-01,0.0
34,field_out,0,Empty,660707,Elehuris Montero,vs_LHP,True,1,0,0,6,True,[0],2024-04-01,0.0
35,field_out,0,Empty,686668,Brenton Doyle,vs_LHP,True,2,0,0,6,True,[0],2024-04-01,0.0
36,single,0,Empty,453568,Charlie Blackmon,vs_LHP,False,2,0,0,6,True,[0],2024-04-01,0.0
37,single,0,Men_On,663898,Brendan Rodgers,vs_LHP,False,2,0,0,6,True,"[0, 1]",2024-04-01,0.0
38,strikeout,0,RISP,666134,Nolan Jones,vs_LHP,True,3,0,0,6,True,"[0, 2, 1]",2024-04-01,0.0
39,single,0,Empty,664023,Ian Happ,vs_RHP,False,0,0,0,6,False,[0],2024-04-01,3.0
40,single,0,Men_On,673548,Seiya Suzuki,vs_RHP,False,0,0,0,6,False,"[0, 1]",2024-04-01,3.0
41,field_out,0,RISP,641355,Cody Bellinger,vs_RHP,True,1,0,0,6,False,"[0, 2, 1]",2024-04-01,3.0
42,single,0,RISP,666624,Christopher Morel,vs_RHP,False,1,3,0,6,False,"[0, 2, 1]",2024-04-01,3.0
43,field_out,0,Empty,621020,Dansby Swanson,vs_RHP,True,2,3,0,6,False,[0],2024-04-01,3.0
44,field_out,0,Empty,683737,Michael Busch,vs_RHP,True,3,3,0,6,False,[0],2024-04-01,3.0
45,field_out,0,Empty,592178,Kris Bryant,vs_RHP,True,1,3,0,7,True,[0],2024-04-01,0.0
46,single,0,Empty,641857,Ryan McMahon,vs_RHP,False,1,3,0,7,True,[0],2024-04-01,0.0
47,field_out,0,Men_On,553869,Elias Díaz,vs_RHP,True,2,3,0,7,True,"[0, 1]",2024-04-01,0.0
48,walk,0,RISP,678662,Ezequiel Tovar,vs_RHP,False,2,3,0,7,True,"[0, 2]",2024-04-01,0.0
49,field_out,0,RISP,660707,Elehuris Montero,vs_RHP,True,3,3,0,7,True,"[0, 3, 1]",2024-04-01,0.0

In [292]:
def getExpectedValue(dataframe):
    out = dataframe.groupby(['runner_pos', 'Outs']).agg({'inningRuns':'mean'})
    return out

In [294]:
EV2024 = getExpectedValue(df)

In [296]:
EV2024

                   inningRuns
runner_pos   Outs
[0, 1]       0       1.786871
             1       0.950559
             2       0.653060
             3       0.392122
[0, 2, 1]    0       2.775904
             1       1.856592
             2       1.323305
             3       0.572218
[0, 2]       0       2.128032
             1       1.364547
             2       1.175333
             3       0.688479
[0, 3, 1]    0       3.283489
             1       2.271059
             2       1.787775
             3       0.823312
[0, 3, 2, 1] 0       4.049505
             1       2.976852
             2       2.336387
             3       0.876475
[0, 3, 2]    0       3.225275
             1       2.417156
             2       1.980640
             3       0.839266
[0, 3]       0       2.485981
             1       1.829545
             2       1.404487
             3       0.695933
[0]          0       0.922515
             1       0.411510
             2       0.332457
             3       0.295302